sudo: required
services:
  - docker

before_install:
  - docker build -t johnetsh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johnetsh/docker-react npm run test -- --coverage

